//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class malfunctions_from_tasks
    {
        public int TaskID { get; set; }
        public int TaskTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> SubPropertyID { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public Nullable<int> ClientClassificationID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public System.DateTime DateForHandling { get; set; }
        public Nullable<bool> IsHandled { get; set; }
        public Nullable<System.DateTime> HandlingDate { get; set; }
        public string HandlingWay { get; set; }
    }
}
