//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<int> SubPropertyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> RentPayment { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<System.DateTime> EnteryDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> ContactRenew { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Property Property { get; set; }
        public virtual SubProperty SubProperty { get; set; }
        public virtual User User { get; set; }
    }
}
